name: 'gp.com'

services:

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - gp.com
    depends_on:
      - django
      - node

  node:
    container_name: node
    build: ./node
    expose:
      - "3000"
    volumes:
      - ./node/src:/app/src
      - ./node/public:/app/public
    restart: on-failure
    networks:
      - gp.com

  # db:
  #   container_name : db
  #   build:
  #     context: ./builds/
  #     dockerfile: Dockerfile_postgres
  #   expose:
  #     - "3001"
  #   restart: on-failure
  #   networks:
  #     - gp.com

  django:
    container_name: django
    build: ./backend
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    restart: on-failure
    networks:
      - gp.com

networks:
  gp.com:
    driver: bridge