name: 'gp.com'

services:

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - db
      - django
      - node
    networks:
      - gp.com

  node:
    container_name: node
    build: ./node
    expose:
      - "3000"
    volumes:
      - ./node/src:/app/src
      - ./node/public:/app/public
    restart: on-failure
    networks:
      - gp.com

  db:
    image: postgres:14-alpine
    container_name : db
    env_file:
      - .env
    expose:
      - "5432"
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - gp.com

  django:
    container_name: django
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:800"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - gp.com

networks:
  gp.com:
    driver: bridge
