# Generated by Django 5.1 on 2024-08-30 08:02

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorId', models.IntegerField(default=0)),
                ('content', models.CharField(default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageAuthor', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='', null=True, upload_to='')),
                ('description_en', models.CharField(default='', max_length=1000)),
                ('description_fr', models.CharField(default='', max_length=1000)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=10), default=list, size=None)),
                ('link', models.CharField(default='', max_length=200)),
                ('integration', models.BooleanField(default=False)),
                ('completion', models.IntegerField(default=0)),
                ('contrib', models.ManyToManyField(related_name='contributors', to='profiles.profile')),
                ('messages', models.ManyToManyField(related_name='messages', to='projects.message')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
                ('authorId', models.IntegerField(default=0)),
                ('accepted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestionAuthor', to='profiles.profile')),
            ],
        ),
    ]
