# Generated by Django 5.1 on 2024-08-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='last_visit',
        ),
        migrations.AddField(
            model_name='project',
            name='messages_read',
            field=models.IntegerField(default=0),
        ),
    ]
