# Generated by Django 5.1 on 2024-08-31 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_message_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
