# Generated by Django 5.1 on 2024-09-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_delete_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='messages_read',
            new_name='comments_read',
        ),
        migrations.RemoveField(
            model_name='project',
            name='messages',
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='projects.message'),
        ),
        migrations.AddField(
            model_name='project',
            name='isCurrent',
            field=models.BooleanField(default=False),
        ),
    ]
