# Generated by Django 5.1 on 2024-09-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_messages_read_project_comments_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completion',
        ),
    ]
