# Generated by Django 5.1.1 on 2024-09-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='integration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
    ]
