# Generated by Django 5.1.1 on 2024-09-14 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_image_remove_project_integration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='authorId',
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
