# Generated by Django 5.1.1 on 2024-09-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_online'),
        ('projects', '0009_remove_message_authorid_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='messageAuthor', to='profiles.profile'),
        ),
    ]
