# Generated by Django 5.1.1 on 2024-09-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_nbofmessages_profile_messages'),
        ('projects', '0010_alter_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='messageAuthor', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
