# Generated by Django 5.1.1 on 2024-09-23 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_comment_responses_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 13, 18, 3, 570624, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='responses',
            field=models.ManyToManyField(to='projects.comment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 13, 18, 3, 571367, tzinfo=datetime.timezone.utc)),
        ),
    ]
