# Generated by Django 5.1.1 on 2024-09-23 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_comment_date_alter_comment_responses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 13, 22, 18, 131851, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 13, 22, 18, 132627, tzinfo=datetime.timezone.utc)),
        ),
    ]
