# Generated by Django 5.1.1 on 2024-09-23 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_comment_date_alter_project_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 13, 23, 41, 197408, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 13, 23, 41, 198168, tzinfo=datetime.timezone.utc)),
        ),
    ]
