# Generated by Django 5.1.1 on 2024-09-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_comment_date_alter_project_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isResponse',
            field=models.BooleanField(default=False),
        ),
    ]
