# Generated by Django 5.1 on 2024-08-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='authorId',
        ),
    ]
