# Generated by Django 5.1 on 2024-09-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backAdmin', '0002_remove_suggestion_authorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='accepted',
            new_name='archived',
        ),
    ]
