# Generated by Django 5.1 on 2024-09-04 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backAdmin', '0003_rename_accepted_suggestion_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
