# Generated by Django 5.1 on 2024-09-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backAdmin', '0004_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fr',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
