# Generated by Django 5.1.1 on 2024-09-23 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backAdmin', '0005_remove_article_content_article_content_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 13, 17, 18, 234516, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='article',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
