# Generated by Django 5.1.1 on 2024-09-23 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backAdmin', '0006_remove_article_creation_date_article_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 13, 18, 3, 574558, tzinfo=datetime.timezone.utc)),
        ),
    ]
