# Generated by Django 5.1.1 on 2024-09-23 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backAdmin', '0007_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 13, 22, 18, 135906, tzinfo=datetime.timezone.utc)),
        ),
    ]
