# Generated by Django 5.1.1 on 2024-09-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backAdmin', '0012_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='bio',
            new_name='bio_en',
        ),
        migrations.AddField(
            model_name='stats',
            name='bio_fr',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
