# Generated by Django 5.1 on 2024-08-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onGoingSuggestion',
            field=models.BooleanField(default=False),
        ),
    ]
