# Generated by Django 5.1 on 2024-08-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_suggested'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chatChannelName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.BooleanField(default=None),
        ),
    ]
