# Generated by Django 5.1 on 2024-09-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_ongoingsuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chatChannelName',
        ),
    ]
