# Generated by Django 5.1 on 2024-08-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
