# Generated by Django 5.1.1 on 2024-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_online'),
        ('projects', '0010_alter_message_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='NbOfMessages',
        ),
        migrations.AddField(
            model_name='profile',
            name='messages',
            field=models.ManyToManyField(related_name='messages', to='projects.message'),
        ),
    ]
