# Generated by Django 5.1.1 on 2024-10-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_messages_profile_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nightMode',
            field=models.BooleanField(default=False),
        ),
    ]
