# Generated by Django 5.1.1 on 2024-10-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default-avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
